DROP DATABASE IF EXISTS FoodCosts;
CREATE DATABASE IF NOT EXISTS FoodCosts;

USE  FoodCosts;

CREATE TABLE IF NOT EXISTS Departments (
DeptName VARCHAR(50) NOT NULL,
PRIMARY KEY (DeptName)
);

CREATE TABLE IF NOT EXISTS FoodItems (
FoodName VARCHAR(50) NOT NULL,
Department VARCHAR(50),
PRIMARY KEY (FoodName),
FOREIGN KEY (Department) REFERENCES Departments(DeptName) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FoodPurchaseHistory (
PurchaseID INT AUTO_INCREMENT NOT NULL,
FoodName VARCHAR(50),
Weight DECIMAL (10,2),
CostPerUnit DECIMAL (10,2),
IsWeighted BOOLEAN,
DatePurchased TIMESTAMP,
PRIMARY KEY (PurchaseID),
FOREIGN KEY (FoodName) REFERENCES FoodItems(FoodName) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS DepartmentCosts (
CostID INT AUTO_INCREMENT NOT NULL,
Food VARCHAR(50),
Department VARCHAR(50),
TotalCost Decimal (10,2),
FOREIGN KEY (Food) REFERENCES FoodItems(FoodName) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (Department) REFERENCES Departments(DeptName) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY (CostID)
);

CREATE TABLE IF NOT EXISTS AverageCosts (
IngCostID INT AUTO_INCREMENT NOT NULL,
Food VARCHAR(50),
AvgCostPerUnit DECIMAL(10,2),
AvgCostPerPound DECIMAL(10,2),
AvgCostPerOunce DECIMAL(10,2),
AvgCostPerCup Decimal(10,2),
FOREIGN KEY (Food) REFERENCES FoodItems(FoodName) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY (IngCostID)
);

CREATE TABLE IF NOT EXISTS Recipes (
MealName VARCHAR(50) NOT NULL,
PRIMARY KEY (MealName)
);

CREATE TABLE IF NOT EXISTS RecipeIngredients (
Ingredient VARCHAR(50),
MealName VARCHAR(50),
AmountUsed DECIMAL(10,2),
AmountUnit VARCHAR(25),
CostPerAmount DECIMAL(10,2),
FOREIGN KEY (Ingredient) REFERENCES FoodItems(FoodName) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (MealName) REFERENCES Recipes(MealName) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY (MealName, Ingredient)
);

-- CREATE TABLE IF NOT EXISTS UnitConversions (
-- FromUnit VARCHAR(20),
-- ToUnit VARCHAR(20),
-- ConversionFactor DECIMAL(10,2),
-- PRIMARY KEY (FromUnit, ToUnit)
-- );
-- USE PYTHON pint